### ISSUE TITLE
Specification should pass potential erros to callback

### ISSUE THREAD

**Issue by markkuriekkinen** [acos-server/acos-server#1]
In the specification, [the section for protocol and the browser library](https://github.com/acos-server/acos-server/blob/master/doc/development.md#browser-library-for-sending-events), the content type may define a callback function when calling `ACOS.sendEvent`. The callback function is supplied only `response.content` as argument, but it should also receive a potential error if the protocol browser library finds out that the server did not receive the (grading) event or the server failed to process the event. In other words, the content type should be able to show error messages to the student if it defines the callback for `ACOS.sendEvent` and uploading the grading results fails because the server is malfunctioning.

**Comment by ttsirkia** [comment]
This is a good point. The possibility for two-way communication was created to enable actions such as server-side grading which can report the grade back to the client. However, this feature has not been used yet and therefore, it is not as complete as it might be.

All the communication between the client-side protocol library and server-side implementation is up to the protocol but I think that there should be a uniform way of reporting errors from `sendEvent` function if it fails. It could be, for example, `{status: 'ERROR'}` or something like that.

Do you @Mankro have any suggestions how to implement this?

**Comment by markkuriekkinen** [comment]
The protocol can respond to the `events.js sendEvent` with `{status: 'ERROR' or 'OK'}` and potentially add more keys to the JSON object to pass a more specific error message when the protocol fails to save the grading properly in the backend. The A+ protocol already uses such status field, but its frontend `events.js` does not read the status at all. When `sendEvent` calls the callback, it could supply two arguments, one of them is the usual `response.content` and the other is an error object (string or Error instance, maybe string is more suitable here; `null/undefined` if there is no error). Alternatively, the error object could be `{}` with fields `status` (like you said) and maybe `message` for details. 

Node.js likes to make the error parameter the first parameter in callbacks, but it could break backwards compatibility in `events.js` or content types that use the callback in `sendEvent`.

**Comment by ttsirkia** [comment]
PRs merged.
