### ISSUE TITLE
Downloading log files with a secret key

### ISSUE THREAD

**Issue by markkuriekkinen** [acos-server/acos-server#5]
[acos-logging-keygenerator](https://github.com/acos-server/acos-logging-keygenerator/blob/master/template.html) suggests that when log files are written with public/secret keypairs (to the directory `public_logs`), one would use the public key in the exercise URL (GET query parameter `logkey`) and the secret key in the URL for downloading the log files via HTTP. However, `acos-server` does not use the secret key and the log files are actually downloaded with the public key (which students may easily see in the exercise HTML). The URL `host.com/logs/SECRETKEY` actually results in HTTP 404 but with the public key it works.

**Comment by ttsirkia** [comment]
It should work as described in the key generator documentation but the implementation does not reflect that. Going to fix this ASAP.

**Comment by ttsirkia** [comment]
Fixed in f07f07cf3727dfc7a7535aa4f3c167fade635cb7
